FROM php:8.2-apache

WORKDIR /var/www

# Installing dependencies
RUN apt-get update && apt-get install -y \
    libpng-dev \
    zip \
    unzip \
    git \
    curl \
    libonig-dev \
    libxml2-dev \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Enabling Apache mod_rewrite
RUN a2enmod rewrite

# Installing Composer
COPY --from=composer:2.6 /usr/bin/composer /usr/bin/composer

# Copying application files
COPY . .

# Installing PHP dependencies
RUN composer install --no-dev --optimize-autoloader

# Setting permissions for storage and cache
RUN chmod -R 777 storage bootstrap/cache

# Exposing port 80 for Apache
EXPOSE 80

CMD ["apache2-foreground"]